"""create association

Revision ID: 223854d88ec3
Revises: cd829c7302ed
Create Date: 2017-04-02 01:38:57.660959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '223854d88ec3'
down_revision = 'cd829c7302ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
