"""further embellish

Revision ID: 2ded0b6bc921
Revises: e8fbcc111024
Create Date: 2017-04-02 11:12:43.968161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ded0b6bc921'
down_revision = 'e8fbcc111024'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orgs', sa.Column('desires', sa.String(), nullable=True))
    op.add_column('orgs', sa.Column('fb', sa.String(), nullable=True))
    op.add_column('orgs', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orgs', 'timestamp')
    op.drop_column('orgs', 'fb')
    op.drop_column('orgs', 'desires')
    # ### end Alembic commands ###
