"""embellish org model more

Revision ID: bfe92fea9295
Revises: 2ded0b6bc921
Create Date: 2017-04-02 11:17:31.484440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfe92fea9295'
down_revision = '2ded0b6bc921'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
