"""add name to org

Revision ID: cd829c7302ed
Revises: e2781ee6c780
Create Date: 2017-04-01 16:43:02.166423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd829c7302ed'
down_revision = 'e2781ee6c780'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orgs', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orgs', 'name')
    # ### end Alembic commands ###
