"""embellish org model

Revision ID: e8fbcc111024
Revises: 223854d88ec3
Create Date: 2017-04-02 10:52:44.390733

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e8fbcc111024'
down_revision = '223854d88ec3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orgs', sa.Column('candidates', sa.String(), nullable=True))
    op.add_column('orgs', sa.Column('email', sa.String(), nullable=True))
    op.add_column('orgs', sa.Column('fiveoone', sa.Boolean(), nullable=True))
    op.add_column('orgs', sa.Column('location', sa.String(), nullable=True))
    op.add_column('orgs', sa.Column('mission', sa.String(), nullable=True))
    op.add_column('orgs', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('orgs', sa.Column('registered', sa.Boolean(), nullable=True))
    op.add_column('orgs', sa.Column('services', sa.String(), nullable=True))
    op.drop_column('orgs', 'features')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orgs', sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('orgs', 'services')
    op.drop_column('orgs', 'registered')
    op.drop_column('orgs', 'phone')
    op.drop_column('orgs', 'mission')
    op.drop_column('orgs', 'location')
    op.drop_column('orgs', 'fiveoone')
    op.drop_column('orgs', 'email')
    op.drop_column('orgs', 'candidates')
    # ### end Alembic commands ###
